# Site settings
title: Krzysztof Maicher
email: krzysztof.maicher@gmail.com
description: ''
baseurl: ''
url: "http://maicher.github.io"
linkedin_username: maicher
twitter_username: kmaicher
github_username:  maicher
stackoverflow_username: 'users/2933305/maicher'
permalink: none
paginate: 10

# Build settings
markdown: kramdown
