gems: [jekyll-paginate]

title: Krzysztof Maicher
email: krzysztof.maicher@gmail.com
description: ''
baseurl: ''
url: "http://maicher.github.io"
google_analytics: 'UA-43848966-7'
permalink: none
markdown: kramdown
paginate_path: "page:num"
paginate: 10

# social media
linkedin_username: maicher
twitter_username: kmaicher
github_username:  maicher
stackoverflow_username: 'users/2933305/maicher'

kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
